const ATTRIBUTE_DISABLED = 0;
const ATTRIBUTE_ENABLED = 1;
const PARSE_INT_RADIX = 10;
const DECIMAL_PLACES_PRICE = 2;
const DECIMAL_PLACES_QUANTITY = 3;
const INITIAL_QUANTITY = 0.000;
const IMAGE_FORMAT_POSITION = 1;
const IMAGE_MAX_SIZE = 4 * 1024 * 1024;

module.exports = {
  ATTRIBUTE_DISABLED,
  ATTRIBUTE_ENABLED,
  PARSE_INT_RADIX,
  DECIMAL_PLACES_PRICE,
  DECIMAL_PLACES_QUANTITY,
  INITIAL_QUANTITY,
  IMAGE_FORMAT_POSITION,
  IMAGE_MAX_SIZE,
};
